/*
-- Query: SELECT * FROM mydb.category
LIMIT 0, 50000

-- Date: 2018-12-06 10:29
*/
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00100','Grocery Miscellaneous');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00130','Frozen Miscellaneous');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00150','Beer Wine Miscellaneous');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00181','BOTTLE DEPOSIT RETURNS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00490','Miscellaneous - Deli Misc');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00500','Miscellaneous - NonFood');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00510','Miscellaneous - HBC');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00520','Miscellaneous - General Merchandise');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00540','Miscellaneous - Candy');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-00580','Miscellaneous - OTC Pharmacy');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01110','BAKERY SNACKS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01120','ENGLISH MUFFINS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01130','FRESH BREAD & ROLLS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01140','PASTRY/DOUGHNUTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01150','PIES & CAKES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01160','PHOTOGRAPHY SUPPLIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01170','LIGHTERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01175','WRITING INSTRUMENTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01176','CHILDRENS ART SUPPLIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01177','OFFICE PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01180','VACUUM BAGS/BELTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01185','HOUSEHOLD PLASTICS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01186','KITCHEN STORAGE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01196','PLAYING CARDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01204','DOUGH/BISCUIT DOUGH - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01208','BAKED GOODS - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01212','BUTTER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01216','NATURAL CHEESE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01217','PROCESSED CHEESE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01218','CREAM CHEESE/CREAM CHEESE SPREAD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01220','COTTAGE CHEESE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01224','CREAMS/CREAMERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01232','DESSERTS - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01236','FRESH EGGS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01240','RFG ENTREES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01241','RFG SIDE DISHES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01244','JUICE/BEVERAGE - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01247','RFG TEAS/COFFEE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01249','LUNCHES - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01252','MARGARINE/SPREADS/BUTTER BLENDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01260','MILK');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01264','PICKLES/RELISH - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01268','PIZZA - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01276','SEAFOOD - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01277','SPREADS - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01280','SOUR CREAM');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01281','DIPS - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01284','YOGURT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01290','RFG TORTLLA/EGGRLL/WONTN WRAP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01299','OTHER RFG PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01310','RFG BACON');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01320','CHEESECAKES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01330','LUNCHEON MEATS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01340','FRANKFURTERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01355','PASTA - RFG');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01370','DINNER SAUSAGE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01399','RFG MEAT/POULTRY PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01401','BABY FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01402','BABY FORMULA/ELECTROLYTES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01404','BAKED BEANS/PORK & BEANS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01407','BAKING MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01410','BAKING NEEDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01411','BAKING CUPS/PAPER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01413','BAKING NUTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01416','BEER & ALE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01419','BOTTLED WATER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01422','BREADCRUMBS/BATTERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01424','TOTAL CHOCOLATE CANDY');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01425','TOTAL NON-CHOCOLATE CANDY');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01428','CARBONATED BEVERAGES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01431','SALTY SNACKS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01432','DIPS - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01434','COCKTAIL MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01440','COFFEE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01443','COFFEE CREAMER - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01446','READY TO EAT CEREAL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01449','COOKIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01452','CRACKERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01455','CROUTONS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01458','DESSERT TOPPINGS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01463','DRY PACKAGED DINNERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01464','SS DINNERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01465','PIZZA PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01467','DRY BEANS/VEGETABLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01470','DRIED FRUIT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01473','DRINK MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01474','NON-FRUIT DRINKS - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01475','MILK FLAVORING/COCOA MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01476','DRY FRUIT SNACKS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01478','EGG SUBSTITUTES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01479','FLOUR/MEAL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01482','FROSTING');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01485','CANNED/BOTTLED FRUIT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01488','GELATIN/PUDDING MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01491','GRAVY/SAUCE MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01494','GUM');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01497','HOT CEREAL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01498','ALL OTHER BREAKFAST FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01499','TOASTER PASTRIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01500','ICE CREAM CONES/MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01501','INSTANT POTATOES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01503','FRUIT BUTTER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01505','ASEPTIC JUICES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01506','BOTTLED JUICES - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01507','CANNED JUICES - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01508','JUICE/DRINK CONCENTRATE - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01509','ISOTONICS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01512','SPIRITS/LIQUOR');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01515','MARSHMALLOWS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01518','MAYONNAISE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01521','CANNED MEAT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01524','MEXICAN FOODS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01525','MEXICAN SAUCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01527','MUSTARD & KETCHUP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01530','MISC SNACKS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01531','SNACK BARS/GRANOLA BARS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01533','ORIENTAL FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01536','PANCAKE MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01539','PASTA');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01542','PEANUT BUTTER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01545','PICKLES/RELISH/OLIVES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01548','POPCORN/POPCORN OIL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01551','EVAPORATED/CONDENSED MILK');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01552','POWDERED MILK');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01554','RICE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01555','RICE/POPCORN CAKES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01557','SALAD DRESSINGS - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01558','SALAD TOPPINGS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01560','ALL OTHER SAUCES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01561','BARBEQUE SAUCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01562','STEAK/WORCESTERSHIRE SAUCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01563','SEAFOOD - SS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01566','SS VEGETABLE/ANIMAL SHORTENING/LARD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01569','SNACK NUTS/SEEDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01572','SOUP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01575','SPAGHETTI/ITALIAN SAUCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01577','FRUIT & VEGETABLE PRESERVATIVE/PECT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01578','SPICES/SEASONINGS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01579','STUFFING MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01581','SUGAR');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01582','SUGAR SUBSTITUTES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01584','MAPLE/PANCAKE & WAFFLE SYRUP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01586','TEA - INSTANT TEA MIXES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01587','TEA - BAGS/LOOSE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01588','TEA - READY-TO-DRINK');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01590','TOMATO PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01593','VEGETABLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01596','VINEGAR');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01598','WINE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01602','FZ BABY FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01604','FZ BREAKFAST FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01608','FZ POULTRY');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01612','FZ COFFEE CREAMER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01620','FZ PREPARED PUDDING/MOUSSE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01624','FZ DINNERS/ENTREES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01628','FZ DOUGH');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01632','FZ FRUIT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01636','JUICES - FROZEN');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01640','FZ MEAT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01644','FZ NOVELTIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01648','FZ PASTA');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01652','FZ BAKED GOODS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01656','FZ PET FOODS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01660','FZ PIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01664','FZ PIZZA');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01668','FZ PLAIN VEGETABLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01669','FZ CORN ON THE COB');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01672','FZ POT PIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01676','FZ POTATOES/ONIONS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01680','FZ PREPARED VEGETABLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01684','FZ SEAFOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01688','FZ SIDE DISHES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01689','FZ APPETIZERS/SNACK ROLLS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01692','ICE CREAM/SHERBET');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01699','OTHER FROZEN FOODS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01704','ADULT INCONTINENCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01705','GASTROINTESTINAL - LIQUID');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01706','GASTROINTESTINAL- TABLETS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01708','ANTI SMOKING FILTER/TABLET');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01712','BABY NEEDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01716','BATH PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01717','BATH/BODY SCRUBBERS/MASSAGERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01718','COLD/ALLERGY/SINUS LIQUIDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01719','COLD/ALLERGY/SINUS TABLETS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01720','CONTRACEPTIVES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01723','COSMETICS - EYE/LIP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01724','COSMETICS - FACIAL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01725','COSMETICS - NAIL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01726','COTTON BALLS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01728','COUGH DROPS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01730','COUGH SYRUP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01732','DEODORANT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01734','TOOTHBRUSH/DENTAL ACCESORIES/REMEDI');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01735','DENTURE PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01736','WEIGHT CONTROL/NUTRITIONALS LIQ/PWD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01738','WEIGHT CONTROL CANDY/TABLETS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01739','EXTERNAL ANALGESIC RUBS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01740','EYE/CONTACT LENS CARE PRODUCT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01742','SKIN CARE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01744','FEMININE NEEDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01745','FAMILY PLANNING');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01748','FIRST AID ACCESSORIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01749','PERSONAL THERMOMETERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01750','FIRST AID TREATMENT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01752','FRAGRANCES - WOMEN\'S');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01754','FOOT CARE PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01755','HAIR COLORING');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01756','HAIR CONDITIONER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01757','HAIR SPRAY/SPRITZ');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01758','HAIR STYLING GEL/MOUSSE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01759','HAND & BODY LOTION');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01760','INTERNAL ANALGESICS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01761','HAIR GROWTH PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01762','MISC HEALTH REMEDY TABLETS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01763','HOME PERMANENT/RELAXER KITS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01764','MISC HEALTH REMEDIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01766','SLEEPING AID TABLET');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01769','MOIST TOWELETTES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01771','MOUTHWASH');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01772','BREATH FRESHENER SPRAYS/DROPS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01773','NASAL PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01774','RAZORS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01775','SANITARY NAPKINS/TAMPONS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01776','SHAMPOO');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01780','SHAVING CREAM/SOAP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01782','SHAVING LOTIONS/MENS FRAGRANCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01788','SUNTAN PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01792','TOOTHPASTE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01796','MULTI VITAMINS/HIPOTENCY/STRESS/CHI');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01802','AIR FRESHENERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01804','BLEACH');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01808','CAT FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01812','CAT LITER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01816','CHARCOAL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01817','CHARCOAL LIGHTER FLUIDS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01820','CIGARETTES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01824','DISPOSABLE CUPS AND PLATES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01825','DISPOSABLE TABLEWARE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01828','DIAPERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01830','PET SUPPLIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01832','DISH DETERGENT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01833','PRODUCT RINSE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01836','DOG FOOD');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01840','FABRIC SOFTENER LIQUID');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01842','FABRIC SOFTENER SHEETS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01844','FACIAL TISSUE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01846','FLOOR CLEANERS/WAX REMOVERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01848','FOILS & WRAPS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01852','FOOD & TRASH BAGS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01854','FURNITURE POLISH');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01856','HOUSEHOLD CLEANER');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01857','HOUSEHOLD CLEANER CLOTHS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01860','LAUNDRY DETERGENT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01861','LAUNDRY CARE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01864','PAPER NAPKINS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01868','PAPER TOWELS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01872','SOAP');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01874','PEST CONTROL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01878','RUG/UPHOLSTERY/FABRIC TREATMENTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01884','SPONGES AND SCOURING PADS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01892','TOBACCO PRODUCTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01894','TOILET TISSUE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01905','MOTOR OIL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01906','AUTOMOBILE FLUIDS/ANTIFREEZE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01907','AUTOMOBILE WAXES/POLISHES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01910','DRY CELL BATTERY');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01913','CLEANING TOOLS/MOPS/BROOMS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01915','SHOE POLISH & ACCESORIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01920','COFFEE FILTERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01925','WATER SOFTENERS/TREATMENT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01940','FOIL PANS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01949','SOCKS AND TIGHTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01950','PANTYHOSE/NYLONS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01960','LIGHT BULBS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01980','WATER FILTERS/DEVICES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01981','HAIR ACCESSORIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01982','BLANK AUDIO/VIDEO CASSETTES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01984','CANDLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01986','COSMETIC STORAGE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01987','SOAP DISHES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01988','PLASTIC BOTTLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01989','TOOTHBRUSH HOLDERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01990','BABY ACCESSORIES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01998','HOUSEHOLD LUBRICANTS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-01999','FIRELOGS/FIRESTARTERS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-20000','LOWES MEAT');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-21000','Lowes Meat - Ground Beef');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-22000','Lowes Meat - Beef');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-23000','Lowes Meat - Pork');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-24000','Lowes Meat - Chicken');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-25000','Lowes Meat - Turkey');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-26000','Lowes Meat - Lamb');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-27000','Lowes Meat - Specialty');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-28000','Lowes Meat - Seafood');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-29000','Lowes Meat - Packaged');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-30000','LOWES PRODUCE');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-31000','LOWES PRODUCE - FRUITS');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-32000','LOWES PRODUCE - VEGETABLES');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-40000','Lowes Deli - Salads');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-41000','Lowes Deli - Salad Bar');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-42000','Lowes Deli - Meats');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-43000','Lowes Deli - Cheese');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-44000','Lowes Deli - Grab-n-Go');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-45000','Lowes Deli - Pizza');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-47000','Lowes Deli - Party Trays');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-48000','Lowes Deli - Hot Food');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-48500','Lowes Deli - Sandwiches');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-49000','Lowes Deli - Miscellaneous');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-49500','Lowes Deli - Beverages');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-50000','Lowes NonFood');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-52000','SEASONAL GM');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-60000','LOWES FLORAL');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-70000','Lowes Bakery - Bakery Rolls');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-71000','Lowes Bakery - Bread');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-72000','Lowes Bakery - Cakes');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-73000','Lowes Bakery - Cookies');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-74000','Lowes Bakery - Doughnuts');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-75000','Lowes Bakery - Pastries');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-76000','Lowes Bakery - Pies');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-77000','Lowes Bakery - Seasonal');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-78000','Lowes Bakery - Miscellaneous');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-79000','Lowes Bakery - Bagels');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-79500','Lowes Bakery - Muffins');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-90000','Lowes Foods PLU Categories');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-99000','Supplies');
INSERT INTO `category` (`CategoryID`,`CategoryName`) VALUES ('02-99999','Coupons');
